apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-test-node
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/zubeyranwar/infra-test-node
    newTag: main
    newName: ghcr.io/zubeyranwar/infra-test-node
