apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-test-react
resources:
  - namespace.yaml
  - nginx-config.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/zubeyranwar/infra-test-react
    newTag: main
    newName: ghcr.io/zubeyranwar/infra-test-react
    digest: sha256:5a9c18d389acbe50c852a0138097f5c8a6694c8f5dc99d9291b5bb4a2c2bb8ec
