apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-test-react
resources:
  - namespace.yaml
  - nginx-config.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/zubeyranwar/infra-test-react
    newTag: main
    newName: ghcr.io/zubeyranwar/infra-test-react
    digest: sha256:db6ca8c13899a64d42ac599f77114d4b2d28e7cf5a7a6ff1530311d2418c0f4d
