apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-test-react
resources:
  - namespace.yaml
  - nginx-config.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/zubeyranwar/infra-test-react
    newTag: main
    newName: ghcr.io/zubeyranwar/infra-test-react
    digest: sha256:b84501168dbca84815b1d11c5c11affd2a09f099d60da6cdfc5cb5258474a7fb
